real_user: "{{ lookup('env', 'SUDO_USER') | default(lookup('env', 'USER')) }}"
real_home: "/home/{{ real_user }}"

apt_packages:
  - git
  - curl
  - wget
  - zsh
  - tmux
  - vim
  - htop
  - unzip
  - build-essential
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gpg
  - flatpak
  - snapd
  - fonts-noto-color-emoji

npm_packages: 
  - typescript
