apt_packages:
  - git
  - curl
  - wget
  - zsh
  - tmux
  - vim
  - htop
  - unzip
  - build-essential
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gpg
  - flatpak
  - snapd
  - npm
  - fonts-noto-color-emoji
